version: '3'

volumes:
  frontend_static_value:
  backend_static_value:
  media_value:
  postgres_data:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: denniraz/foodgram_backend
    env_file: .env
    volumes:
      - backend_static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db

  frontend:
    image: denniraz/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - frontend_static_value:/static

  nginx:
    image: denniraz/foodgram_nginx
    ports:
      - "80:80"
    volumes:
      - frontend_static_value:/usr/share/nginx/html/
      - backend_static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
